ingestion_jobs:
  - job_name: "description_ingestion"
    duckdb_name: "assignment.duckdb"
    duckdb_schema: "bronze"
    duckdb_table: "description"
    excel_path: "Data/Raw/DataScientist_CaseStudy_Dataset.xlsx"
    excel_sheetname: "Description"

  - job_name: "soc_dem_ingestion"
    duckdb_name: "assignment.duckdb"
    duckdb_schema: "bronze"
    duckdb_table: "soc_dem"
    excel_path: "Data/Raw/DataScientist_CaseStudy_Dataset.xlsx"
    excel_sheetname: "Soc_Dem"

  - job_name: "products_actbalance_ingestion"
    duckdb_name: "assignment.duckdb"
    duckdb_schema: "bronze"
    duckdb_table: "products_actbalance"
    excel_path: "Data/Raw/DataScientist_CaseStudy_Dataset.xlsx"
    excel_sheetname: "Products_ActBalance"

  - job_name: "inflow_outflow_ingestion"
    duckdb_name: "assignment.duckdb"
    duckdb_schema: "bronze"
    duckdb_table: "inflow_outflow"
    excel_path: "Data/Raw/DataScientist_CaseStudy_Dataset.xlsx"
    excel_sheetname: "Inflow_Outflow"

  - job_name: "sales_revenues_ingestion"
    duckdb_name: "assignment.duckdb"
    duckdb_schema: "bronze"
    duckdb_table: "sales_revenues"
    excel_path: "Data/Raw/DataScientist_CaseStudy_Dataset.xlsx"
    excel_sheetname: "Sales_Revenues"